version: "3.8"

services:
  frontend:
    network_mode: host
    env_file: .env
    build:
      network: host
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./:/react-app:delegated
#      - /node_modules
    #    ports:
    #      - "7000:7000"
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      REACT_APP_BASE_URL_DEV: ${REACT_APP_BASE_URL_DEV}
      REACT_APP_CHAT_BASE_URL: ${REACT_APP_CHAT_BASE_URL}
      REACT_APP_CHAT_BASE_URL_DEV: ${REACT_APP_CHAT_BASE_URL_DEV}
      REACT_APP_TORRENT_BASE_URL: ${REACT_APP_TORRENT_BASE_URL}
      REACT_APP_TORRENT_BASE_URL_DEV: ${REACT_APP_TORRENT_BASE_URL_DEV}
      PORT: ${PORT}
